### ISSUE TITLE
Bridge Mode Info

### ISSUE THREAD

**Issue by corincorvus** [louislam/uptime-kuma-wiki#48]
Hi,

i tried your Documentation for Monitoting Docker Containers and the daemon.json didnt work.
I got your error with duplicate, but i couldnt solve it with your solution.
https://github.com/louislam/uptime-kuma-wiki/blob/master/How-to-Monitor-Docker-Containers.md

So i tested other Solutions and the Solution, it worked on my Debian Bookworm, i want to share.

if i edit: sudo systemctl edit docker.service
i get this information: 
### Anything between here and the comment below will become the new contents of the file

So i created the docker.service.d folder and open the new file override.conf

In the override.conf i add:
```toml
[Service]
#The blank ExecStart is required to clear the current entry point
ExecStart=
#Replace the existing ExecStart but only remove the properties that you have added into the daemon.json file, leave all else the same.
#ExecStart=/usr/local/bin/dockerd --containerd=/run/containerd/containerd.sock
ExecStart=/usr/sbin/dockerd -H tcp://0.0.0.0:2375 -H fd:// --containerd=/run/containerd/containerd.sock $DOCKER_OPTS
```
for testing.

After i add certificate:
```toml
[Service]
#The blank ExecStart is required to clear the current entry point
ExecStart=
#Replace the existing ExecStart but only remove the properties that you have added into the daemon.json file, leave all else the same.
#ExecStart=/usr/local/bin/dockerd --containerd=/run/containerd/containerd.sock
ExecStart=/usr/sbin/dockerd --tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H tcp://0.0.0.0:2375 -H fd:// --containerd=/run/containerd/containerd.sock $DOCKER_OPTS
```

it work fine:
![image](https://github.com/louislam/uptime-kuma-wiki/assets/21257329/1574d6b0-4789-4d44-baee-77dad8391fa3)
![image](https://github.com/louislam/uptime-kuma-wiki/assets/21257329/6eeb66e9-6edd-46c8-a472-b02ed39eaf4f)

I hope someone will help this.

Thanks
